### ISSUE TITLE
Allow full file name override

### ISSUE THREAD

**Issue by jmacdonald** [AndyBarron/preferences-rs#18]
Right now, there are two options for a preference file name: 

* `<key>.prefs.json`
* `prefs.json`

It would be great to be able to override this, so that _any_ file name can be chosen (some linux utilities use a `.config/app_name/config` pattern, which is currently impossible). At very least, if full control over the extension is undesirable, being able to avoid the `.prefs` extension prefix when using a non-empty key would be great!

**Comment by andybarron** [comment]
You can always use [`app_dirs`](https://github.com/andybarron/app-dirs-rs).

My vision for this lib is to make things as simple and config-free as possible for the developer; theoretically, the storage implementation could be encapsulated/platform-dependent, like Java's [Preferences API](https://docs.oracle.com/javase/8/docs/api/java/util/prefs/Preferences.html). So the mapping from key to filename isn't something that consumers of *this particular lib* should be worrying about.

I'm not drawing a line in the sand or anything -- if somebody made a PR adding this (with a clean API), I'd  consider it. But I don't think it's something I'll get around to adding myself, especially since I already maintain [`app_dirs`](https://github.com/andybarron/app-dirs-rs), which would let you do this (and more).

**Comment by jmacdonald** [comment]
Makes sense!
