### ISSUE TITLE
Add a `config` equivalent

### ISSUE THREAD

**Issue by gyscos** [AndyBarron/preferences-rs#7]
Not all user-specific preferences should go to `XDG_DATA_HOME`, configuration for instance could go to `XDG_CONFIG_HOME`. Much of the structure is the same, though (serializable key-value pairs), so it may make sens to include this in this crate.

Among the few differences between preference and config, I'd say more option in the serialization format would be helpful (some people will really like `toml` for configuration, but not necessarily for preferences).

**Comment by passcod** [comment]
I'd argue that _all_ user preferences should go to XDG_CONFIG_HOME. XDG_DATA_HOME is for, well, data. Like if you were building a Twitter client, preferences would go in `~/.config/rustytweet/*.json`, cached images and media from timelines would go in `~/.cache/rustytweet/media`, and, say, Tweet drafts would go in `~/.local/share/rustytweet/drafts/`.

For a real example, the Evolution mail client has ini-style account configs in `~/.config/evolution/sources/`, local IMAP temporary mail/calendar/addressbook cache in `~/.cache/evolution/<type>/` in various formats (XML, MBOX, etc), and permanent mail/calendar/etc data in `~/.local/share/evolution/<type>/` (POP3 mail, ICS calendar files, local mail trash, etc).

**Comment by andybarron** [comment]
I was initially against offering multiple variants/options for config vs data, but I'm warming up to the idea.

One issue: What to do on platforms like Windows that (AFAIK) don't differentiate between user data & config. On Linux, you'd get two separate files for config and data:
- Key: `developer/appname`
  - Config path: `~/.config/developer/appname`
  - Data path: `~/.local/share/developer/appname`

But then on Windows, you'd get a conflict:
- Key: `developer/appname`
  - Config path: `%APPDATA%/developer/appname`
  - Data path: `%APPDATA%/developer/appname`

This would be bad because your config and data would overwrite each other. Possible solutions:
- Prefix: `%APPDATA%/{config,data}/developer/appname`
- Suffix: `%APPDATA%/developer/appname.{cfg,dat}`

I'm leaning heavily towards the latter option, since both OS X and Windows specify that all your application data should be grouped in the same folder. It makes the mapping of prefs key -> file path less straightforward, but we don't make any guarantees about that anyway, so I think it should be fine?

**Comment by andybarron** [comment]
Also, if we do decided to go down this path, I will likely factor out a lot of this logic into a new crate modeled after [appdirs](https://github.com/ActiveState/appdirs), then make that crate a dependency of preferences-rs.

**Comment by gyscos** [comment]
As @passcod says, maybe it's not up to this library to handle data, and it should keep to config? Much of what is called "preference" is often configuration anyway (User data will rarely be called preference, but maybe "saved profile" or something, and will often be more complex than a json file). It may make things simpler, rather than having both options.

**Comment by andybarron** [comment]
That's actually a great point; non-preference data will probably need to be stored in a format other than JSON anyway. Alright, this is sounding good :)

I think that making an appdirs-like library will be great for arbitrary/cache data, and preferences can just focus on JSON-encodable user prefs.

**Comment by passcod** [comment]
:+1:

**Comment by gyscos** [comment]
Sounds good. I still think more serialization options (ini, toml) could be very helpful there. And if you don't want to bloat applications with non-needed dependencies (though I doubt `rust-ini` or `toml-rs` are that big), conditional dependencies based on crate feature could probably help. Though that's for another ticket.

**Comment by andybarron** [comment]
I would imagine that people could just grab the appdirs-like crate and their serialization library of choice and go to town, with preferences being sort of an extension to appdirs that takes care of the encoding/decoding for you. I'll consider it for inclusion, though, especially once conditional dependencies hit Rust stable!

**Comment by andybarron** [comment]
Crate [app_dirs](https://github.com/AndyBarron/app-dirs-rs) is now available ([published to Cargo](https://crates.io/crates/app_dirs)) for general-purpose storage of arbitrary app data (config, cache, etc.). I'll be moving forward with preferences-rs as the "opinionated" solution for preferences and config data.
